language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sanjeevthakur/docker-react -f Dockerfile.dev .  

script:
  - docker run -e CI=true sanjeevthakur/docker-react npm run test